# Generated by Django 2.2.7 on 2020-02-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_topic', models.CharField(max_length=400)),
                ('post_content', models.CharField(max_length=2000)),
                ('post_startdate', models.DateField()),
                ('post_starttime', models.DateTimeField()),
                ('post_endtime', models.DateTimeField()),
                ('post_startaddress', models.CharField(max_length=200)),
                ('post_endaddress', models.CharField(max_length=200)),
                ('post_coachbox', models.IntegerField()),
                ('post_transposts', models.CharField(max_length=300)),
                ('post_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
