# Generated by Django 2.2.7 on 2020-02-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uppost',
            old_name='post_coachbox',
            new_name='coachbox',
        ),
        migrations.RenameField(
            model_name='uppost',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='uppost',
            old_name='post_endaddress',
            new_name='endaddress',
        ),
        migrations.RenameField(
            model_name='uppost',
            old_name='post_endtime',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='uppost',
            old_name='post_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='uppost',
            old_name='post_startaddress',
            new_name='startaddress',
        ),
        migrations.RenameField(
            model_name='uppost',
            old_name='post_startdate',
            new_name='startdate',
        ),
        migrations.RenameField(
            model_name='uppost',
            old_name='post_starttime',
            new_name='starttime',
        ),
        migrations.RenameField(
            model_name='uppost',
            old_name='post_topic',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='uppost',
            old_name='post_transposts',
            new_name='transposts',
        ),
    ]
