# Generated by Django 2.2.7 on 2020-02-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200221_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uppost',
            name='image',
            field=models.ImageField(upload_to='course_pictures'),
        ),
    ]
